apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-for-create
  resourceVersion: "{{metadata.resourceVersion}}"
  uid: "{{metadata.uid}}"
  labels:
    app: updated-app
    version: v2
spec:
  params:
    - name: greeting
      type: string
      default: "Updated greeting"
    - name: recipient
      type: string
      default: "World"
  steps:
    - name: print-greeting
      image: registry.redhat.io/ubi9/ubi-minimal
      script: |
        #!/bin/bash
        echo "$(params.greeting), $(params.recipient)!"
    - name: print-timestamp
      image: registry.redhat.io/ubi9/ubi-minimal
      script: |
        #!/bin/bash
        date
