apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-for-create
spec:
  params:
    - name: greeting
      type: string
      default: "Original greeting"
  steps:
    - name: print-greeting
      image: registry.redhat.io/ubi9/ubi-minimal
      script: |
        #!/bin/bash
        echo "$(params.greeting)"
